fs.makeDir('/lib')
fs.makeDir('/lib/lib')
fs.makeDir('/lib/lib/turtle_explorer_api')
fs.makeDir('/lib/lib/turtle_explorer_api/autocomplete')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/autocomplete/locations.lua /lib/lib/turtle_explorer_api/autocomplete/locations.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/autocomplete/travel.lua /lib/lib/turtle_explorer_api/autocomplete/travel.lua')
fs.makeDir('/lib/lib/turtle_explorer_api/bin')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/bin/locations.lua /lib/lib/turtle_explorer_api/bin/locations.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/bin/scheduler.lua /lib/lib/turtle_explorer_api/bin/scheduler.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/bin/travel.lua /lib/lib/turtle_explorer_api/bin/travel.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/blocks.lua /lib/lib/turtle_explorer_api/blocks.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/heap.lua /lib/lib/turtle_explorer_api/heap.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/maps.lua /lib/lib/turtle_explorer_api/maps.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/tasker.lua /lib/lib/turtle_explorer_api/tasker.lua')
fs.makeDir('/lib/lib/turtle_explorer_api/tasks')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/tasks/explorer.lua /lib/lib/turtle_explorer_api/tasks/explorer.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/tasks/go_to.lua /lib/lib/turtle_explorer_api/tasks/go_to.lua')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/lib/turtle_explorer_api/tracker.lua /lib/lib/turtle_explorer_api/tracker.lua')
fs.makeDir('/lib/startup')
shell.run('wget https://github.com/MrVoustache/TurtleExplorerAPI/raw/refs/heads/main/source/startup/init_scheduler.lua /lib/startup/init_scheduler.lua')
